version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: document_processing_app_simple
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
